name: Model training and deployment

on:
  push:
    branches:
      - master

jobs:
  run-cnn:
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            
      - name: Run script
        run: python run_model.py
